# ATTENTION: no deployment should be done until serverless.yml is properly setup
name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.yml'
      - 'package.json'
      - 'layer/**'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
jobs:
  # scan code using CodeQL
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  test:
    name: test
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test
  syntax-check:
    name: syntax-check
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm i
    - name: serverless check
      uses: serverless/github-action@master
      with:
        args: deploy --noDeploy
  deploy:
    runs-on: ubuntu-latest
    needs: [test, syntax-check]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm i
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: --version
