name: init
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    if: github.repository != 'kaskadi/template-kaskadi-layer'
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: bash .github/workflows/scripts/init.sh
